name: Flake8

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake8:
    uses: flightless-ops/flightless-ci/.github/workflows/flake8.yml@main
    with:
      python-version: '3.12'
      target-path: '.'
