name: MyPy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  mypy:
    uses: flightless-ops/flightless-ci/.github/workflows/mypy.yml@main
    with:
      python-version: '3.12'
      target-path: '.'
