name: Pylint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pylint:
    uses: flightless-ops/flightless-ci/.github/workflows/pylint.yml@main
    with:
      python-version: '3.12'
      target-path: '.'
