name: Pytest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    uses: flightless-ops/flightless-ci/.github/workflows/pytest.yml@main
    with:
      python-version: '3.12'
      target-path: '.'
      package-name: 'flightless_pylint_plugin'
